### ISSUE TITLE
Cannot find files on external drive

### ISSUE THREAD

**Issue by Jomy10** [nobohan/OpenArdenneMap#14]
I'm trying to generate a map using this project.

I installed like follows (on a fresh Ubuntu install):
```sh
# As sudo
apt-get update -y
apt-get install -y \
	ca-certificates \
	gnupg \
	libmapnik3.1 \
	libmapnik-dev \
	mapnik-utils \
	python3-mapnik \
	python3-numpy \
	python3-psycopg2 \
	python3-svgwrite \
	python3-wand \
	python3-pyx \
	osm2pgsql \
	curl \
	nodejs \
	npm \
	postgresql-15 \
	postgresql-server-dev-15 \
	postgresql-client-15 \
	postgis \
	postgresql-15-postgis-3

# CartoCSS
npm install carto -g

# Setup Postgres
chown postgres:postgres /run/postgresql
cp install2.sh /var/lib/postgresql/install2.sh
chown postgres:postgres /var/lib/postgresql/install2.sh
mkdir /var/lib/postgresql/data
chown postgres:postgres /var/lib/postgresql/data

su postgres
cd /var/lib/postgresql
export PATH="$PATH:/usr/lib/postgresql/15/bin"
initdb -D /var/lib/postgresql/data
pg_ctl start -D /var/lib/postgresql/data

# OpenArdenneMap #
git clone https://github.com/nobohan/OpenArdenneMap
cd OpenArdenneMap

# Setup database
cd osm2pgsql
sh create-db.sh
cd ..

# Styles
carto osm2pgsql/project.mml > osm2pgsql/OpenArdenneMap.xml
carto osm2pgsql/project-labels.mml > osm2pgsql/OpenArdenneMap-labels.xml
carto osm2pgsql/project-background.mml > osm2pgsql/OpenArdenneMap-background.xml
```

I then download map data and insert it into the database:
```sh
# Download data
curl -L http://download.geofabrik.de/europe/united-kingdom/scotland-latest.osm.pbf -o scotland.osm.pbf

# Update database
osm2pgsql -c -G --slim -d osmpg_db -S osm2pgsql/OpenArdenneMap.style --extra-attributes scotland.osm.pbf
```

Then I edit center coordinates in `templates/marked_trails/parameters.py` and try to generate the map:
```sh
cd templates/marked_trails
python3 main.py
```

But when I do that, I get the following error:
```
ERROR 4: /mnt/tera/ChampsLibres/Projets/OSM/CyclOSM/hillshade/data/dem_be_10x10_hillshade_semi_transparent_3857.tif: No such file or directory
Traceback (most recent call last):
  File "/var/lib/postgresql/OpenArdenneMap/templates/marked_trails/main.py", line 46, in <module>
    make_map(
  File "/var/lib/postgresql/OpenArdenneMap/templates/marked_trails/../../makeMap.py", line 34, in make_map
    load_map(m, mapnik_file)
RuntimeError: /mnt/tera/ChampsLibres/Projets/OSM/CyclOSM/hillshade/data/dem_be_10x10_hillshade_semi_transparent_3857.tif: No such file or directory  encountered during parsing of layer 'hillshade' in Layer at line 959 of '/var/lib/postgresql/OpenArdenneMap/osm2pgsql/OpenArdenneMap-background.xml'
```

Seems like it is using a file from an external drive, but this is not documented anywhere on how to acquire these files.

**Comment by nobohan** [comment]
Hello. Indeed you need to have a geotiff of a hillshade to render this layer. I cannot include this geotiff in the repo since it can be huge. The same apply for the contour line layer just below. 

For Belgium, you can download hillshade and contour lines from these addresses: http://opendata.champs-libres.be/hillshade_belgium.zip and http://opendata.champs-libres.be/beautiful-contour-belgium.zip. (See this blog post in French for some context: https://www.champs-libres.coop/blog/post/2020-06-24-beautiful-hillshade-belgium/)

For other part of the world, well, this is not always easy to find such resources (hillshade and contour lines). You can find some digital elevation model (DEM) and derive hillshade and contour lines. There are global DEM available from ESA or NASA. Here's a guide for producing hillshade and contour from a DEM: https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/HOWTO_DEM.md. But this is not straight-forward or done in 5 minutes...

Of course you can disable these two layers (set the status to "off").

Sorry this is missing in the README, I'll put it ASAP.

**Comment by Jomy10** [comment]
Thank you for the response, I'll keep experimenting. Feel free to close this issue now (I'll leave it in case you still want to keep it upon until you update the README)
